spring.application.name=comprasprocesadorms
spring.datasource.url=jdbc:postgresql://localhost:5432/ucoshopdb
spring.datasource.username=postgres
spring.datasource.password=000
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=false

sales.queues.response.create.ex=sales.response
sales.queues.response.create.rk=create
sales.queues.response.create.qn=sales.response.create

sales.queues.response.update.ex=sales.response
sales.queues.response.update.rk=update
sales.queues.response.update.qn=sales.response.update

# Bills
sales.queues.bill.create-exchange-name=comprasprocesador.bill.crear.ex
sales.queues.bill.create-routing-key=comprasprocesador.bill.crear.rk
sales.queues.bill.create-queue-name=comprasprocesador.bill.crear.qn

sales.queues.bill.delete-exchange-name=comprasprocesador.bill.delete.ex
sales.queues.bill.delete-routing-key=comprasprocesador.bill.delete.rk
sales.queues.bill.delete-queue-name=comprasprocesador.bill.delete.qn

# Sale
sales.queues.sale.create-exchange-name=comprasprocesador.sales.crear.ex
sales.queues.sale.create-routing-key=comprasprocesador.sales.crear.rk
sales.queues.sale.create-queue-name=comprasprocesador.sales.crear.qn

# Cart
sales.queues.cart.add-item-ex=procesadorcompras.cart.additem.ex
sales.queues.cart.add-item-rk=procesadorcompras.cart.additem.rk
sales.queues.cart.add-item-qn=procesadorcompras.cart.additem.qn

sales.queues.cart.reduce-item-ex=procesadorcompras.cart.reduceitem.ex
sales.queues.cart.reduce-item-rk=procesadorcompras.cart.reduceitem.rk
sales.queues.cart.reduce-item-qn=procesadorcompras.cart.reduceitem.qn

sales.queues.cart.delete-item-ex=procesadorcompras.cart.deleteitem.ex
sales.queues.cart.delete-item-rk=procesadorcompras.cart.deleteitem.rk
sales.queues.cart.delete-item-qn=procesadorcompras.cart.deleteitem.qn

sales.queues.cart.clear-ex=procesadorcompras.cart.clear.ex
sales.queues.cart.clear-rk=procesadorcompras.cart.clear.rk
sales.queues.cart.clear-qn=procesadorcompras.cart.clear.qn
