spring.application.name=comprasprocesadorms
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.datasource.url=jdbc:postgresql://localhost:5432/ucoshopdb
spring.datasource.username=postgres
spring.datasource.password=000
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Bills
sales.queues.bill.create.ex=sales.bill
sales.queues.bill.create.rk=create
sales.queues.bill.create.qn=sales.bill.create

sales.queues.bill.delete.ex=sales.bill
sales.queues.bill.delete.rk=delete
sales.queues.bill.delete.qn=sales.bill.delete

# Sale
sales.queues.sale.create.ex=sales.sale
sales.queues.sale.create.rk=create
sales.queues.sale.create.qn=sales.sale.create

# Cart
sales.queues.cart.create.ex=sales.cart
sales.queues.cart.create.rk=create
sales.queues.cart.create.qn=sales.cart.create

sales.queues.cart.add-item.ex=sales.cart
sales.queues.cart.add-item.rk=add-item
sales.queues.cart.add-item.qn=sales.cart.add-item

sales.queues.cart.reduce-item.ex=sales.cart
sales.queues.cart.reduce-item.rk=reduce-item
sales.queues.cart.reduce-item.qn=sales.cart.reduce-item

sales.queues.cart.delete-item.ex=sales.cart
sales.queues.cart.delete-item.rk=delete-item
sales.queues.cart.delete-item.qn=sales.cart.delete-item

sales.queues.cart.clear.ex=sales.cart
sales.queues.cart.clear.rk=clear
sales.queues.cart.clear.qn=sales.cart.clear



